resume_parser/resume_app/urls.py
from django.urls import path
from . import views

app_name = 'resume_app'

urlpatterns = [
    #path('', views.react_frontend, name='react_frontend'),
    path('', views.upload_resume, name='upload_resume'),
    path('process/', views.process_resume, name='process_resume'),
    path('resume-analysis/', views.resume_analysis, name='resume_analysis'),
   # path('react/', views.react_frontend, name='react_frontend'),  # Add this URL pattern
    # Add other URL patterns as needed
    # Add other URL patterns as needed
]

#urlpatterns = [
#    path('', views.upload_resume, name='upload_resume'),
    # Add other URL patterns as needed
#]

resume_parser/resume_parser/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', include('resume_app.urls')),
]

# Serve static files in development (for DEBUG = True)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resume_parser/resume_app/models.py
from django.db import models

# Create your models here.

resume_parser/resume_app/views.py
import os
from django.shortcuts import render
from django.http import JsonResponse
from pyresparser import ResumeParser
import json
from django.core.files.storage import FileSystemStorage
from .resume_analysis import analyze_resume

def react_frontend(request):
    return render(request, 'index.html')

def upload_resume(request):
    return render(request, 'upload_resume.html')

def process_resume(request):
    print("Processing resume")
    if request.method == 'POST' and request.FILES['resume']:
        resume = request.FILES['resume']
        fs = FileSystemStorage()
        filename = fs.save(resume.name, resume)
        resume_path = fs.path(filename)
        print(f"Resume path: {resume_path}")
        data = ResumeParser(resume_path).get_extracted_data()
        print(f"Extracted data: {data}")

        # Analyze the resume and get the predicted job role
        predicted_job_role = analyze_resume(resume_path)

        # Add the predicted job role to the data dictionary
        data['predicted_job_role'] = predicted_job_role

        # File Path and Appending Data
        file_path = os.path.join(os.path.dirname(__file__), 'static', 'resume_data.json')

        # Create or clear the file before adding new data
        with open(file_path, 'w') as file:
            pass

        resume_json = json.dumps(data)
        with open(file_path, 'a') as file:
            file.write(resume_json + "\n")

        # Remove the PDF file
        os.remove(resume_path)

        return JsonResponse(data)  # Return the data as JSON response

    return render(request, 'upload_resume.html')

def resume_analysis(request):
    # Your code for resume analysis goes here
    return render(request, 'resume_analysis.html')

resume_parser/resume_app/templates/index.html
<!-- templates/index.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>React App</title>
</head>
<body>
    <!-- Render the React app here -->
    <div id="root"></div>

    <!-- Load the React app's JavaScript files -->
    <script src="{% static 'js/runtime-main.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

resume_parser/resume_app/templates/result.html
<!DOCTYPE html>
<html>
<head>
    <title>Resume Result</title>
</head>
<body>
    <h1>Resume Result</h1>
    <p>Candidate Name: {{ data.name }}</p>
    <p>Email: {{ data.email }}</p>
    <p>College: {{ data.college }}</p>
    <p>Phone: {{ data.mobile_number }}</p>
    <p>Skills: {{ data.skills }}</p>
    <p>Experience: {{ data.experience }}</p>
    <p>Designation: {{ data.designation }}</p>
    <p>Address: {{ data.address }}</p>
    <p>Company Name: {{ data.company_name }}</p>
</body>
</html>

resume_parser/resume_app/templates/upload_resume.html
<!DOCTYPE html>
<html>
<head>
    <title>Upload Resume</title>
</head>
<body>
    <h1>Upload Resume</h1>
    <form method="post" action="{% url 'resume_app:process_resume' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="resume" accept=".pdf,.doc,.docx">
        <input type="submit" value="Upload">
    </form>
</body>
</html>